uint8 mode
geometry_msgs/PointStamped start
geometry_msgs/PointStamped target
float64 corridor_width_x
float64 corridor_width_y
---
std_msgs/Header header
float64 target_z
float64 path_max_z
float64 path_min_z
float64 data_age_sec
int32 status
