drivers:
  seyond:
    - enable: true
      config: seyond_1.yaml
      name: seyond_1
    - enable: true
      config: seyond_2.yaml
      name: seyond_2

warehouse:
  cloud_grid:
    enable: true
  vol_cal:
    enable: true
  feeding_vol_cal:
    enable: true
  device_status:
    enable: true
  las_exporter:
    enable: true

cranes: [0, 1, 2]

lidar_crane_map:
  1: 1
  2: 1
  3: 2
  4: 2
  5: 0
  6: 0
  7: 0

crane_nodes:
  0:
    ws_bridge:
      enable: true
  1:
    picking_area:
      enable: true
    height_service:
      enable: true
    ws_bridge:
      enable: true
  2:
    picking_area:
      enable: true
    height_service:
      enable: true
    ws_bridge:
      enable: true
