warehouse_id: 3
resolution_x: 0.1
resolution_y: 0.1
sparse_resolution_x: 0.5
sparse_resolution_y: 0.5
workspace_min_pt:
  x: 0.0
  y: 8.25
  z: -7.0
workspace_max_pt:
  x: 160.0
  y: 24.0
  z: 4.7
crane_id_list: [0, 1, 2]
fixed_lidar_sn_list: [5, 6, 7]
