common:
  log_level: info                                     #Log level: info, warn, error
lidars:
  - lidar:
      frame_topic: /seyond/lidar_10_35_0_116                       #Frame topic

      lidar_name: seyond_116                              #Lidar name
      lidar_ip: 10.35.0.116                          #Lidar ip
      port: 8010                                      #Lidar port
      udp_port: 8013                                  #Udp port, if < 0, use tcp
      receive_mode: 1
  - lidar:
      frame_topic: /seyond/lidar_10_35_0_117                       #Frame topic

      lidar_name: seyond_117                              #Lidar name
      lidar_ip: 10.35.0.117                              #Lidar ip
      port: 8010                                      #Lidar port
      udp_port: 8014                                 #Udp port, if < 0, use tcp
      receive_mode: 1
