lidar_id: 1
topic_lidar_cloud: /livox/lidar_192_168_41_129
topic_lidar_transform: surface_clouds_lidar_
crane_id: 1
warehouse_id: 1
fixed_lidar_flag: 0
fixed_lidar_x: 0.0
scan_min:
  x: -5.0
  y: -3.0
  z: -10.0
scan_max:
  x: 5.0
  y: 3.0
  z: 10.0
trans:
  [1.0, 0.0, 0.0, 0.0,
   0.0, 1.0, 0.0, 0.0,
   0.0, 0.0, 1.0, 0.0,
   0.0, 0.0, 0.0, 1.0]
